# Futuristic Unminimal Starship Prompt
format = """
[â•­](fg:blue bold) ğŸ›¸ \
$hostname  $directory  $git_branch  $git_status  $kubernetes  $shell  $time \
\n$character
"""

# Palette
palette = "gruvbox"

[palettes.gruvbox]
color_fg0 = "#ebdbb2"
color_bg0 = "#3C4841"
color_bg1 = "#3c3836"
color_bg2 = "#504945"
color_bg3 = "#665c54"
color_blue = "#458588"
color_aqua = "#689d6a"
color_green = "#98971a"
color_orange = "#d65d0e"
color_red = "#cc241d"
color_yellow = "#d79921"
color_magenta = "#b16286"

# Prompt end character
[character]
format = "[â•°â”€$symbol](fg:blue bold)"
success_symbol = "ïƒš"
error_symbol = "ïƒš"

# Hostname
[hostname]
disabled = false
ssh_only = false
format = "[ğŸ–¥ $hostname](fg:color_blue bold) "

# Directory with icon and truncation
[directory]
format = "[ó°‰‹ $path](fg:color_fg0 bold) "
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™"
"Downloads" = "ï€™"
"Music" = "ï€"
"Pictures" = "ï€¾"
"Desktop" = "ï„ˆ"

# Git branch
[git_branch]
disabled = false
symbol = "î‚ "
style = "fg:color_yellow bold"
format = "[$symbol $branch]($style) î‚±"

[git_status]
disabled = false
format = "[$stagedâ—$unstagedâœš$untrackedâ€¦]($style) î‚±"
style = "fg:color_green bold"

# Kubernetes context
[kubernetes]
disabled = false
style = "fg:color_blue bold"
format = "[â›µ $context in $namespace]($style) î‚±"

[shell]
disabled = true
style = "fg:color_aqua bold"
format = "[ï„  $symbol $version]($style)"

# Time
[time]
disabled = false
time_format = "%R"
style = "fg:color_aqua bold"
format = "[â° $time]($style) î‚±"
